[[constraint]]
  name = "github.com/go-redis/redis"
  version = "6.12.0"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "v1.2.2"

[[constraint]]
  name = "github.com/spotahome/kooper"
  version = "v0.8.0"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.15.6"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.15.6"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.15.6"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.15.6"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  branch = "master"
